use modern API in addFavIcon
adobe/helix-project-boilerplate pull request #212
Opened 2023-04-26 17:38 UTC by synox

Based on https://javascript.info/modifying-document#summary these are also “old school” methods.

Simplifies the code, easier to understand.

2023-04-27 19:42 UTC, rofe requested changes

2023-04-27 19:42 UTC, rofe commented on scripts/scripts.js
> -  }
I think this bracket should have stayed

2023-04-27 20:28 UTC, synox commented on scripts/scripts.js
> -  }
oops! fixed

2023-05-02 16:59 UTC, synox commented
@rofe done

2023-05-06 09:05 UTC, rofe commented
@synox great, now all that's left to do is adding the test URL to the description for the last check to turn green.

2023-05-08 07:56 UTC, rofe commented
Changes included in #214.

2023-05-08 07:56 UTC, closed without merging