chore: initial nav refactor
adobe/helix-project-boilerplate pull request #82
Opened 2022-04-25 20:43 UTC by davidnuescheler

this is a refactor that changes the content structure of the nav to something that seems more inline with the DOM that is semantically correct....

https://nav-refactor--helix-project-boilerplate--adobe.hlx.page/nav-new.plain.html

vs.

https://main--helix-project-boilerplate--adobe.hlx.page/nav.plain.html

to illustrate a very common tools section i added and search icon and also implemented the `icon` handling that embeds the SVG into the DOM.

there are a few other aspects with respect to the color setup to further unclever things... i didn't spend too much time thinking about it, as know that @fkakatie will probably refactor this anyway.

2022-04-27 19:09 UTC, rofe requested changes
Can you fix the `stylelint` issues?

2022-05-02 17:48 UTC, rofe approved these changes

2022-05-09 07:07 UTC, rofe approved these changes

2022-05-09 07:07 UTC, rofe commented on blocks/header/header.js
> +  const navPath = cfg.nav || '/nav-new';
I assume we would revert that before merging?

2022-05-09 07:07 UTC, rofe commented on blocks/header/header.js
> +  if (resp.status === 200) {
```suggestion
  if (resp.ok) {
```
Might also include `304`

2022-05-09 07:32 UTC, kptdobe approved these changes

2022-05-16 03:38 UTC, merged