feat: custom 404 example
adobe/helix-project-boilerplate pull request #99
Opened 2022-05-24 21:36 UTC by fkakatie

add sample 404 page

- attempting to balance simplicity with visual interest (my hope is that the "0" is somewhat reminiscent of a faulty helix strand)
- a "go back" button will be added in addition to the "go home" button if there is a `document.referrer` and its origin matches the `window.location`'s origin

Fix #63 

Test URLs:
- Before: https://main--helix-project-boilerplate--adobe.hlx.page/error
- After: https://404--helix-project-boilerplate--adobe.hlx.page/error

2022-05-25 08:03 UTC, kptdobe requested changes
Independently of liking the design or not, I think it is important to build the page in a way that nothing has to be done when creating a new project (no project name to update, no url to adjust...).
Looking at this nice page with the rotating Helix, I somehow changed my mind and tend to agree with @davidnuescheler regarding extra simplicity: every project will have its own custom 404 page... at one point. Building that page will certainly not be the priority, the default one will be there for a while and even potentially go-live initially. It should then be a nice clean page that would be an acceptable default for every project.

2022-05-25 22:39 UTC, rofe approved these changes
Too bad I missed the version with the rotating helix! 😄

2022-06-02 07:00 UTC, trieloff approved these changes

2022-06-07 07:28 UTC, kptdobe approved these changes

2022-06-20 22:57 UTC, davidnuescheler approved these changes

2022-06-20 23:03 UTC, merged